### ISSUE TITLE
Bimodal behaviour to be captured in noise metric

### ISSUE THREAD

**Issue by acreskeyMoz** [mozilla/measure-noise#4]
Sometimes we see bimodal load times in raptor test results, eg:
<img width="1047" alt="bimodal load" src="https://user-images.githubusercontent.com/44072237/60522972-ebc4c400-9cb7-11e9-8c7b-a58b33da8e19.png">

This view shows the results of multiple cold load runs (15 replicates for each).
There are 1-2 very slow loads per run in this scenario.

This issue to capture the bimodal loads in the noise measurement.

**Comment by gmierz** [comment]
For this issue, it could be interesting to see if k-means can provide anything towards a noise measurement.

**Comment by klahnakoski** [comment]
I have now included bimodal data.  Both balanced, and unbalanced

**Comment by klahnakoski** [comment]
https://github.com/mozilla/measure-noise/pull/9
